# Generated by Django 4.1.7 on 2023-03-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='profile.jpg', upload_to=''),
        ),
    ]
