# Generated by Django 4.1.7 on 2023-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='book_author',
            field=models.CharField(default='john doe', max_length=100),
        ),
    ]
