# Generated by Django 4.1.7 on 2023-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('book_author', models.CharField(default='john doe', max_length=100)),
                ('slug', models.SlugField(verbose_name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>')),
                ('body', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('thumb', models.ImageField(blank=True, default='profile.jpg', upload_to='')),
            ],
        ),
    ]
