# Generated by Django 4.1.7 on 2023-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>'),
        ),
    ]
