# Generated by Django 4.1.7 on 2023-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_remove_sell_author_remove_sell_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='phone',
            field=models.TextField(default=0),
        ),
    ]
