# Generated by Django 4.1.7 on 2023-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_alter_sell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='book_slug',
            field=models.TextField(default=0),
        ),
    ]
