# Generated by Django 4.1.7 on 2023-03-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_sell_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='book_slug',
        ),
    ]
